[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

upload_port = COM5
monitor_port = COM5

upload_speed = 115200

lib_deps =
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.17
    madhephaestus/ESP32Servo @ ^3.0.5
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.15

build_flags =
    -DCORE_DEBUG_LEVEL=0